# Generated by Django 5.0.6 on 2024-05-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='avg_rating',
            field=models.CharField(default=5, max_length=20),
        ),
    ]
