# Generated by Django 5.0.6 on 2024-06-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_products_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='keywords',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
